Text = str(input('Введите строку: '))
print(Text)
print(Text[2])
print(Text[-2])
print(Text[0:5])
print(Text[0:len(Text) -2])
print(Text[:-2])
print(Text[0::2])
print(Text[1::2])
print(Text[::-1])
print(Text[::-2])
print(len(Text))